In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
myarr=np.arange(1000000)
mlst=list(range(1000000))

In [9]:
%time for _ in range(10): myarr2 = myarr * 2

Wall time: 40 ms


In [10]:
%time for _ in range(10): mlst2 = mlst * 2

Wall time: 392 ms


### The NumPy ndarray: A Multidimensional Array Object

In [254]:
# genarate some random numbers
data=np.random.randn(2,3)
data

array([[ 1.1466868 , -1.71310794,  1.09745724],
       [ 0.71654016, -1.50327097,  0.58198413]])

### mathematical operations

In [257]:
data * 10

array([[ 11.46686798, -17.13107941,  10.97457238],
       [  7.16540157, -15.03270967,   5.81984132]])

In [258]:
data + data

array([[ 2.2933736 , -3.42621588,  2.19491448],
       [ 1.43308031, -3.00654193,  1.16396826]])

An ndarray is a generic multidimensional container for homogeneous data; that is, all
of the elements must be the same type. Every array has a shape, a tuple indicating the
size of each dimension, and a dtype, an object describing the data type of the array:

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

### Creating ndarrays

Whenever you see “array,” “NumPy array,” or “ndarray” in the text,
with few exceptions they all refer to the same thing: the ndarray
object.

The easiest way to create an array is to use the array function. This accepts any
sequence-like object (including other arrays) and produces a new NumPy array containing the passed data.

In [20]:
a1 = [6, 7.5, 8, 0, 1]
ar1 = np.array(ar)
ar1

array([6. , 7.5, 8. , 0. , 1. ])

In [22]:
print(type(ar1))

<class 'numpy.ndarray'>


In [24]:
a2 = [[1,2,3,4],[5,6,7,8]]
ar2 = np.array(a2)
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Since a2 was a list of lists, the NumPy array arr2 has two dimensions with shape
inferred from the data.\
We can confirm this by inspecting the ndim and shape
attributes:

In [25]:
ar2.ndim

2

In [26]:
ar2.shape

(2, 4)

In addition to np.array, there are a number of other functions for creating new 
arrays. 
As examples, zeros and ones create arrays of 0s or 1s, respectively, with a 
given length or shape. empty creates an array without initializing its values to any particular value.\
To create a higher dimensional array with these methods, pass a tuple \
for the shape:

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

arange is an array-valued version of the built-in Python range function:

In [31]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

The data type or dtype is a special object containing the information (or metadata,
data about data) the ndarray needs to interpret a chunk of memory as a particular
type of data:

In [32]:
arr1 = np.array([1,2,3], dtype=float)
arr2 = np.array([1,2,3], dtype=np.int64)

In [33]:
arr1.dtype

dtype('float64')

In [34]:
arr2.dtype

dtype('int64')

you can explicitly convert or cast an array from one dtype to another using ndarray's astype method

In this example, integers are cast to floating point

In [35]:
arr = np.array([1,3,5,2,4,6])

In [36]:
arr.dtype

dtype('int32')

In [37]:
float_arr = arr.astype(np.float64)

In [38]:
float_arr.dtype

dtype('float64')

Using astype to covert array of strings into numeric form

In [40]:
num_str = np.array(['1', '2.5', '-4'])
num_str.astype(np.float64)

array([ 1. ,  2.5, -4. ])

You can also use another array’s dtype attribute:

In [41]:
int_arr = np.arange(10)
points = np.array([.11, .185, .227, .400])

In [42]:
int_arr.astype(points.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Arithmetic operation with NumPy Arrays

In [43]:
arr = np.array([(1.,2.,3.), (4.,5.,6.)])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [44]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [45]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
arr2 = np.array([(0.,1.,2.), (4.,6.,7.)])
arr2

array([[0., 1., 2.],
       [4., 6., 7.]])

In [47]:
arr2 > arr

array([[False, False, False],
       [False,  True,  True]])

### Indexing and Slicing

NumPy array indexing is a rich topic, as there are many ways to select
a subset of the data or individual elements. One-dimensional arrays are simple, 
it act similarly to Python lists:


In [65]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr[2]

2

In [67]:
arr[4:9]

array([4, 5, 6, 7, 8])

In [76]:
arr[4:7] = 29

In [77]:
arr

array([ 0,  1,  2,  3, 29, 29, 29,  7,  8,  9])

In [78]:
slice_arr = arr[4:7]
slice_arr

array([29, 29, 29])

below we see, changing values in slice_arr reflects mutations in the ariginal array arr

In [79]:
slice_arr[2] = 2021
arr

array([   0,    1,    2,    3,   29,   29, 2021,    7,    8,    9])

[:] assigns to all values in array

In [80]:
slice_arr[:] = 92
arr

array([ 0,  1,  2,  3, 92, 92, 92,  7,  8,  9])

In a two-dimensional
array, the elements at each index are no longer scalars but rather one-dimensional
arrays:

In [82]:
arr2d = np.array([(20,21,22),(30,31,31),(40,41,42)])
arr2d[1]

array([30, 31, 31])

In [84]:
arr2d[1][2]

31

In [86]:
arr2d[2][2]

42

In [88]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [90]:
arr3d[0] # arr3d is a 2x3 array

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
# both scalar values and arrays can be assigned to arr3d[0]
val = arr3d[0].copy()

In [92]:
arr3d[0] = 50

In [93]:
arr3d

array([[[50, 50, 50],
        [50, 50, 50]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [94]:
arr3d[0] = val
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

arr3d[1, 0] gives all the values whose indices start with (1, 0),
forming a 1-dimensional array:

In [95]:
arr3d[1,0]

array([7, 8, 9])

### Real and Imaginary parts

In [96]:
data = np.array([1,2,3], dtype=complex)
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [98]:
data.real

array([1., 2., 3.])

In [99]:
np.imag(data)

array([0., 0., 0.])

### Arrays filled with constant values

The functions np.zeros and np.ones create and return arrays filled with zeros and ones,
respectively. They take, as first argument, an integer or a tuple that describes the number
of elements along each dimension of the array. For example, to create a 2 × 3 array filled
with zeros, and an array of length 4 filled with ones, we can use

In [100]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [101]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

Like other array-generating functions, the np.zeros and np.ones functions also
accept an optional keyword argument that specifies the data type for the elements in the
array. By default, the data type is float64, and it can be changed to the required type by
explicitly specifying the dtype argument.

In [102]:
data=np.ones(5)
data.dtype

dtype('float64')

In [103]:
data=np.ones(5, dtype=np.int64)
data.dtype

dtype('int64')

An array filled with an arbitrary constant value can be generated by first creating
an array filled with ones and then multiplying the array with the desired fill value.
However, NumPy also provides the function np.full that does exactly this in one step.

In [108]:
a1 = 4.8 * np.ones(10)
a2 = np.full(10, 4.8)

In [109]:
a2

array([4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8])

An already created array can also be filled with constant values using the np.fill
function, which takes an array and a value as arguments, and set all elements in the array
to the given value. The following two methods to create an array therefore give the same
results:

In [110]:
a1 = np.empty(4)
a1.fill(2.1)
a1

array([2.1, 2.1, 2.1, 2.1])

In [111]:
a2 = np.full(4, 2.1)
a2

array([2.1, 2.1, 2.1, 2.1])

### Arrays Filled with Incremental Sequences

In numerical computing it is very common to require arrays with evenly spaced values
between a starting value and ending value. NumPy provides two similar functions to
create such arrays: np.arange and np.linspace. Both functions take three arguments,
where the first two arguments are the start and end values. The third argument of
np.arange is the increment, while for np.linspace it is the total number of points
in the array.

In [112]:
# to generate arrays with values between 1 and 10, with increment 1, we can use arange or linspace
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [116]:
# using linspace
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

np.arange does not include the end value (10), while by default
np.linspace does (using parameter endpoint = True). It is generally recommended to use np.linspace whenever the
increment is a noninteger.

### Arrays Filled with Logarithmic Sequences

The function np.logspace is similar to np.linspace, but the increments between the
elements in the array are logarithmically distributed, and the first two arguments, for
the start and end values, are the powers of the optional base keyword argument (which
defaults to 10). For example, to generate an array with logarithmically distributed values
between 1 and 1000, we can use

In [122]:
np.logspace(0,3,6) # 6 data points between 10**0=1 to 10**3=1000

array([   1.        ,    3.98107171,   15.84893192,   63.09573445,
        251.18864315, 1000.        ])

### Meshgrid Arrays

Multidimensional coordinate grids can be generated using the function np.meshgrid.
Given two one-dimensional coordinate arrays (i.e., arrays containing a set of coordinates
along a given dimension), we can generate two-dimensional coordinate arrays using the
np.meshgrid function.

In [124]:
x = np.array([-1,0,1])
y = np.array([-2,0,2])
x,y=np.meshgrid(x,y)
x

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [125]:
y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

A common use-case of the two-dimensional coordinate arrays, of x and y in the above
example, is to evaluate functions over two variables x and y. This can be used when
plotting functions over two variables, as colormap plots and contour plots.

### Creating Uninitialized Arrays

the function np.empty creates an array of specific size and data type, without initializing it.
The advantage of using this function is that we can avoid the initiation step. If all elements are
guaranteed to be initialized later in the code, this can save a little bit of time, especially
when working with large arrays.

In [128]:
np.empty(3)

array([0., 0., 0.])

### Creating Arrays with Properties of Other Arrays

In [131]:
#def f(x): 
#    y = np.ones_like(x) # a new array y is created using np.ones_like, which results in an array of the same size and data type as x, and filled with on
#    return y

### Matrix Arrays

Matrices, or two-dimensional arrays, are an important case for numerical computing.

the
function np.identity generates a square matrix with ones on the diagonal and zeros 

In [133]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

The similar function numpy.eye generates matrices with ones on a diagonal
(optionally offset). 

In [134]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [135]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

To construct a matrix with an arbitrary one-dimensional array on the diagonal, we
can use the np.diag function

In [136]:
np.diag(np.arange(0,16,4)) # third argument specifies the step size

array([[ 0,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  8,  0],
       [ 0,  0,  0, 12]])

###  Multidimensional arrays

In [145]:
f = lambda m, n: n+10*m
a = np.fromfunction(f,(6,6), dtype=int)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [146]:
a[:,3] # 4th column

array([ 3, 13, 23, 33, 43, 53])

In [147]:
a[2,:] # 3rd row

array([20, 21, 22, 23, 24, 25])

By applying a slice on each of the array axes, we can extract subarrays (submatrices
in this two-dimensional example):

In [150]:
a[:3,:3] # upper left half

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [151]:
a[:3,3:] # upper right half

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25]])

In [152]:
a[3:,:3] # lowerleft half

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [153]:
a[3:,3:] # lower right half

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

In [156]:
a[::2,::2] # ecery 2nd element starting from loc 0,0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [161]:
a[1::2, 1::3] # every 2nd and 3rd element starting from 1,1

array([[11, 14],
       [31, 34],
       [51, 54]])

### Reshaping and Resizing

Reshaping an array does not require modifying the underlying array data; it only
changes in how the data is interpreted, by redefining the array’s strides attribute.
In NumPy, the function np.reshape, or the ndarray class method
reshape, can be used to reconfigure how the underlying data is interpreted. It takes an
array and the new shape of the array as arguments:

This example demonstrates two different ways
of invoking the reshape operation: using the function np.reshape and the ndarray
method reshape. Note that reshaping an array produces a view of the array, and if an
independent copy of the array is needed, the view has to be copied explicitly

In [163]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [164]:
np.reshape(data,(1,4))

array([[1, 2, 3, 4]])

In [165]:
data.reshape(4)

array([1, 2, 3, 4])

The np.ravel is a special case of reshape, which collapses all the dimensions of the array and returns a flattened one dimensional array with a length that corresponds to the total number of elements in the original
array. ndarray method flatten performs the same function but returns a copy
instead of a view

In [167]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [168]:
data.flatten()

array([1, 2, 3, 4])

In [169]:
data.flatten().shape

(4,)

It is also possible to introduce new axes into an array, either by using np.reshape
or, when adding new empty axes, using indexing notation and the np.newaxis keyword
at the place of a new axis.

In [173]:
data = np.arange(0,5)
data

array([0, 1, 2, 3, 4])

In [174]:
col = data[:, np.newaxis]
col

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [175]:
row = data[np.newaxis,:]
row

array([[0, 1, 2, 3, 4]])

### Boolean Indexing

In [298]:
names = np.array(['Rahul', 'Bruce', 'Jack','Rahul', 'Jack', 'Bruce', 'Bruce'])

In [299]:
data = np.random.randn(7,4)

In [300]:
names

array(['Rahul', 'Bruce', 'Jack', 'Rahul', 'Jack', 'Bruce', 'Bruce'],
      dtype='<U5')

In [301]:
data

array([[ 0.51788482,  1.9063252 ,  0.36295379, -0.55168262],
       [ 2.64472813, -0.41868457, -0.0274055 , -1.41981807],
       [ 0.95235476,  0.33685335, -1.33389768, -0.28519978],
       [ 0.59711034, -1.48430226, -0.80619747, -0.65207706],
       [-1.15512631, -1.25619034, -1.43720608, -0.21985849],
       [ 1.97861677, -0.13493215, -0.36572606, -0.25352648],
       [ 0.17300364,  0.45364752, -0.41714512,  1.28530699]])

Suppose each name corresponds to a row in the data array and we wanted to select
all the rows with corresponding name 'Bob'. Like arithmetic operations, compari‐
sons (such as ==) with arrays are also vectorized. Thus, comparing names with the
string 'Rahul' yields a boolean array:

In [302]:
names == 'Rahul'

array([ True, False, False,  True, False, False, False])

This boolean array can be passed when indexing the array:

The boolean array must be of the same length as the array axis it’s indexing. You can
even mix and match boolean arrays with slices or integers (or sequences of integers;
more on this later).

In [303]:
data[names == 'Rahul']

array([[ 0.51788482,  1.9063252 ,  0.36295379, -0.55168262],
       [ 0.59711034, -1.48430226, -0.80619747, -0.65207706]])

In these examples, I select from the rows where names == 'Rahul' and index the columns, too:

In [304]:
data[names == 'Rahul',2:]

array([[ 0.36295379, -0.55168262],
       [-0.80619747, -0.65207706]])

In [305]:
data[names == 'Rahul',3]

array([-0.55168262, -0.65207706])

To select everything except 'Rahul', you can either use != or negate the condition using ~:

In [306]:
names != 'Rahul'

array([False,  True,  True, False,  True,  True,  True])

In [307]:
data[~(names == 'Rahul')]

array([[ 2.64472813, -0.41868457, -0.0274055 , -1.41981807],
       [ 0.95235476,  0.33685335, -1.33389768, -0.28519978],
       [-1.15512631, -1.25619034, -1.43720608, -0.21985849],
       [ 1.97861677, -0.13493215, -0.36572606, -0.25352648],
       [ 0.17300364,  0.45364752, -0.41714512,  1.28530699]])

The ~ operator can be useful when you want to invert a general condition:

In [308]:
cond = names == 'Rahul'

In [309]:
data[~cond]

array([[ 2.64472813, -0.41868457, -0.0274055 , -1.41981807],
       [ 0.95235476,  0.33685335, -1.33389768, -0.28519978],
       [-1.15512631, -1.25619034, -1.43720608, -0.21985849],
       [ 1.97861677, -0.13493215, -0.36572606, -0.25352648],
       [ 0.17300364,  0.45364752, -0.41714512,  1.28530699]])

Selecting two of the three names to combine multiple boolean conditions, use
boolean arithmetic operators like & (and) and | (or):

In [310]:
mask = (names == 'Rahul') | (names == 'Jack')

In [311]:
mask

array([ True, False,  True,  True,  True, False, False])

In [312]:
data[mask]

array([[ 0.51788482,  1.9063252 ,  0.36295379, -0.55168262],
       [ 0.95235476,  0.33685335, -1.33389768, -0.28519978],
       [ 0.59711034, -1.48430226, -0.80619747, -0.65207706],
       [-1.15512631, -1.25619034, -1.43720608, -0.21985849]])

Selecting data from an array by boolean indexing always creates a copy of the data,
even if the returned array is unchanged.

Setting values with boolean arrays works in a common-sense way. To set all of the
negative values in data to 0 we only need to do:

In [313]:
data[data < 0] = 0
data

array([[0.51788482, 1.9063252 , 0.36295379, 0.        ],
       [2.64472813, 0.        , 0.        , 0.        ],
       [0.95235476, 0.33685335, 0.        , 0.        ],
       [0.59711034, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [1.97861677, 0.        , 0.        , 0.        ],
       [0.17300364, 0.45364752, 0.        , 1.28530699]])

Setting whole rows or columns using a one-dimensional boolean array is also easy:

In [314]:
data[names != 'Bruce'] = 7

In [315]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [2.64472813, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.97861677, 0.        , 0.        , 0.        ],
       [0.17300364, 0.45364752, 0.        , 1.28530699]])

these types of operations on two-dimensional data are convenient
to do with pandas.

### Fancy Indexing

Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.
Suppose we had an 8 × 4 array:

In [324]:
arr = np.empty((8,4))

In [332]:
for i in range(8):
    arr[i] = i

In [333]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

To select out a subset of the rows in a particular order, you can simply pass a list or
ndarray of integers specifying the desired order:

In [335]:
arr[[0,3,4,7]]

array([[0., 0., 0., 0.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [7., 7., 7., 7.]])

Passing multiple index arrays does something slightly different; it selects a onedimensional array of elements corresponding to each tuple of indices:

In [337]:
arr = np.arange(32)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [338]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [343]:
arr[[1,3,7,4],[2,1,0,3]]

array([ 6, 13, 28, 19])

In [353]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

unlike slicing, fancy indexing always copies the data into a new
array

### Transpose Arrays and Swapping Axes

Transposing is a special form of reshaping that similarly returns a view on the under‐
lying data without copying anything. Arrays have the transpose method and also the
special T attribute:

In [354]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [355]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [356]:
arr = np.random.randn(6,3)
arr

array([[ 2.59879765e+00, -7.06059944e-01,  7.81908021e-01],
       [-5.56851587e-01, -2.03679447e-02,  2.20061670e-02],
       [ 6.48481290e-01, -5.60365676e-04,  8.36049258e-02],
       [ 1.16225675e+00,  3.01690036e-01,  4.62668085e-02],
       [-1.70427820e+00, -1.25446890e+00, -1.68135272e-01],
       [-1.90239621e-01, -5.31228944e-01, -1.64949540e-01]])

In [359]:
np.dot(arr.T,arr)

array([[11.77595694,  0.76573768,  2.44568591],
       [ 0.76573768,  2.44584909, -0.24006433],
       [ 2.44568591, -0.24006433,  0.67647265]])

For higher dimensional arrays, transpose will accept a tuple of axis numbers to per‐
mute the axes (for extra mind bending):

In [360]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [366]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In the above example, the axes have been reordered with the second axis first, the first axis second,
and the last axis unchanged

Simple transposing with .T is a special case of swapping axes. ndarray has the method
swapaxes, which takes a pair of axis numbers and switches the indicated axes to rear‐
range the data:

In [367]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [368]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])